# Generated by Django 5.0.3 on 2024-10-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('number_of_questions', models.IntegerField(default=4)),
                ('correct_answer', models.IntegerField(unique=True)),
            ],
        ),
    ]
