# Generated by Django 5.0.3 on 2024-10-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.IntegerField(default=0),
        ),
    ]
