# Generated by Django 5.0.3 on 2024-10-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_quiz_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='solutions',
            field=models.ManyToManyField(related_name='solutions', to='quizes.solution'),
        ),
    ]
