# Generated by Django 5.0.3 on 2024-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_quiz_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='solutions', to='quizes.solution'),
        ),
    ]
