# Generated by Django 5.0.3 on 2024-10-08 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_alter_quiz_solutions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='solutions',
            field=models.ManyToManyField(blank=True, null=True, related_name='solutions_quiz', to='quizes.solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_solution', to='quizes.quiz'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
