# Generated by Django 5.0.3 on 2024-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='quiz',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
