# Generated by Django 5.0.3 on 2024-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_registeruser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users_register', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions_register', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
