# Generated by Django 5.0.3 on 2024-10-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizes', '0005_alter_quiz_solutions'),
        ('users', '0002_remove_registeruser_password2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes_solutions', to='quizes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes_solutions_user', to='users.registeruser')),
            ],
            options={
                'unique_together': {('quiz', 'user')},
            },
        ),
    ]
